//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int UserTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
